version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: ribiro
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: ribiro-project3-database.cfa7ulwuxact.us-east-1.rds.amazonaws.com
      POSTGRES_DB: postgres
      AWS_BUCKET: ribiro-project3-bucket
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      JWT_SECRET: project3
      URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: ribiro
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: ribiro-project3-database.cfa7ulwuxact.us-east-1.rds.amazonaws.com
      POSTGRES_DB: postgres
      AWS_BUCKET: ribiro-project3-bucket
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      JWT_SECRET: project3
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend
    ports:
      - "8100:80"
