apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
        - image: ribiro/udagram-api-user
          name: backend-user
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
