apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 3
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
        - image: ribiro/udagram-api-feed
          name: backend-feed
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
